version: "3.9"


services:
    web-server:
        image: nginx:1.23.4
        container_name: student-management-nginx
        ports:
            - "19000:80"
        volumes:
            - ./_dev/config/servers/:/etc/nginx/conf.d/

    php:
        build:
            dockerfile: Dockerfile
            context: .
        image: php8.2-fpm
        container_name: student-management-php
        
        ports:
            - "9000:9000"

    db:
        image: mysql:8.0.26
        container_name: student-management-mysql
        volumes:
            - ./_dev/config/mysql_db:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        ports:
            - "3308:3306"
